.PHONY: clean All

All:
	@echo "----------Building project:[ vForStudent - Debug ]----------"
	@cd "vForStudent" && "$(MAKE)" -f  "vForStudent.mk"
clean:
	@echo "----------Cleaning project:[ vForStudent - Debug ]----------"
	@cd "vForStudent" && "$(MAKE)" -f  "vForStudent.mk" clean
